### ISSUE TITLE
Copyright text

### ISSUE THREAD

**Issue by AndersSpringborg** [aau-datsw/How-to-deploy-your-first-software#1]
Jeg har taget det meste a [den her paper](https://paper.dropbox.com/doc/How-to-build-your-server--A9V4bMr7YVS2K1gRlUqZSZu6Ag-NCJD9eTyRzH1Gy1cXhHoM) som du har skrevet Brams. Jeg har opdateret billederne, da jeg ikke vidste, om du ville have dem oppe. Hvordan skal jeg lige give dig anderkendelse / shoutout på at du har skrevet det?

**Comment by Minibrams** [comment]
Fedt at I kan bruge det! 
Det er sødt af dig at du vil give et shoutout - et link til min GitHub er mere end fint :) 
Knæk og bræk med RUSLAN - det bliver så fedt.

**Comment by AndersSpringborg** [comment]
❤️
